# Generated by Django 5.0.9 on 2024-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imprimir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NAME', max_length=255)),
            ],
            options={
                'db_table': 'INVENTORY',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
    ]
