# Generated by Django 5.0.9 on 2024-11-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imprimir', '0002_maquina_delete_leitor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquina',
            table='_SMDBA_._INVENTORY_',
        ),
    ]
