# Generated by Django 5.0.9 on 2024-11-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imprimir', '0003_alter_maquina_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquina',
            table='_INVENTORY_',
        ),
    ]
