# Generated by Django 5.0.9 on 2024-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imprimir', '0007_alter_maquina_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquina',
            table='TI._SMDBA_._INVENTORY_',
        ),
    ]
