# Generated by Django 5.0.9 on 2024-11-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imprimir', '0012_alter_maquina_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquina',
            table='[_SMDBA_].[_INVENTORY_]',
        ),
    ]
